### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by tshemsedinov** [Kirillbiliashov/Coursework#1]
- Try to decompose long lines with the help of intermediate variables: https://github.com/Kirillbiliashov/Coursework/blob/d8572cd21d5db017d74b25a9c3a15628b7c89ba6/project/src/Card.java#L25
  - `2` is a magic
- Nested ternary is not a good idea: https://github.com/Kirillbiliashov/Coursework/blob/d8572cd21d5db017d74b25a9c3a15628b7c89ba6/project/src/Player.java#L103
- When you use `{}` block for if statement, you need to add `{}` block for else too: https://github.com/Kirillbiliashov/Coursework/blob/d8572cd21d5db017d74b25a9c3a15628b7c89ba6/project/src/Player.java#L103
- Use intermediate variables in cases like this: https://github.com/Kirillbiliashov/Coursework/blob/d8572cd21d5db017d74b25a9c3a15628b7c89ba6/project/src/RoundHandler.java#L106-L107
- Use return early in cases like this: https://github.com/Kirillbiliashov/Coursework/blob/d8572cd21d5db017d74b25a9c3a15628b7c89ba6/project/src/WinnersHandler.java#L18

**Comment by Kirillbiliashov** [comment]
OK, all fixed (especially huge lines of code), thanks for review 🤝
